In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from datetime import datetime

In [2]:
df = pd.read_excel('6118149_OGR3NI9A.xlsx', sheet_name=1)

In [5]:
df[df['free_Кол-во водителей'] == df['free_Кол-во водителей'].max()]

,Дата,free_Кол-во водителей,free_Время (сек),order_driving_Кол-во водителей,order_driving_Время (сек),order_waiting_Кол-во водителей,order_waiting_Время (сек),order_transporting_Кол-во водителей,order_transporting_Время (сек),offline_Кол-во водителей,offline_Время (сек),Всего_Кол-во водителей,Всего_Время (сек)
115,2017-08-16 19:00:07.420,1638,1156849,1252,680480,1211,377618,1362,1952367,2647,3392100,2769,7559414

In [6]:
df[df['free_Кол-во водителей'] == df['free_Кол-во водителей'].min()]

,Дата,free_Кол-во водителей,free_Время (сек),order_driving_Кол-во водителей,order_driving_Время (сек),order_waiting_Кол-во водителей,order_waiting_Время (сек),order_transporting_Кол-во водителей,order_transporting_Время (сек),offline_Кол-во водителей,offline_Время (сек),Всего_Кол-во водителей,Всего_Время (сек)
52,2017-08-14 03:59:59.740,143,109765,94,57831,89,26907,98,151050,627,1407622,641,1753175

In [28]:
df['oder_total'] = df['order_driving_Время (сек)'] + df['order_waiting_Время (сек)'] + df['order_transporting_Время (сек)']
df['oder_total']
df['offline_free_total'] = df['free_Время (сек)'] + df['offline_Время (сек)']
df['offline_free_total']

df['соотношение'] = df['oder_total']/df['offline_free_total']
df['соотношение']

df[(df['Дата'] >= '2017-08-16 00:00:00.000') & (df['Дата'] < '2017-08-17 00:00:00.000')].head()

,Дата,free_Кол-во водителей,free_Время (сек),order_driving_Кол-во водителей,order_driving_Время (сек),order_waiting_Кол-во водителей,order_waiting_Время (сек),order_transporting_Кол-во водителей,order_transporting_Время (сек),offline_Кол-во водителей,offline_Время (сек),Всего_Кол-во водителей,Всего_Время (сек),oder_total,offline_free_total,соотношение
97,2017-08-16 00:59:59.515,412,420617,252,128812,241,86747,288,335356,1070,1750019,1109,2721551,550915,2170636,0.253803
98,2017-08-16 01:59:59.510,279,325821,173,89864,170,60283,206,233208,828,1512765,866,2221941,383355,1838586,0.208505
99,2017-08-16 02:59:59.505,240,364276,123,58697,118,38561,129,145625,727,1603487,763,2210646,242883,1967763,0.123431
100,2017-08-16 04:00:00.000,203,262664,108,59198,106,36665,113,138002,680,1363156,713,1859685,233865,1625820,0.143844
101,2017-08-16 05:00:00.490,277,329550,153,72439,142,46621,143,147429,790,1528233,825,2124272,266489,1857783,0.143445

In [26]:
df[df['free_Кол-во водителей'] == df['free_Кол-во водителей'].max()]

,Дата,free_Кол-во водителей,free_Время (сек),order_driving_Кол-во водителей,order_driving_Время (сек),order_waiting_Кол-во водителей,order_waiting_Время (сек),order_transporting_Кол-во водителей,order_transporting_Время (сек),offline_Кол-во водителей,offline_Время (сек),Всего_Кол-во водителей,Всего_Время (сек),oder_total,offline_free_total,соотношение
115,2017-08-16 19:00:07.420,1638,1156849,1252,680480,1211,377618,1362,1952367,2647,3392100,2769,7559414,3010465,4548949,0.661794

In [30]:
df['oder_avrg'] = df['order_waiting_Время (сек)']/df['order_waiting_Кол-во водителей']
df[df['oder_avrg'] == df['oder_avrg'].max()]

,Дата,free_Кол-во водителей,free_Время (сек),order_driving_Кол-во водителей,order_driving_Время (сек),order_waiting_Кол-во водителей,order_waiting_Время (сек),order_transporting_Кол-во водителей,order_transporting_Время (сек),offline_Кол-во водителей,offline_Время (сек),Всего_Кол-во водителей,Всего_Время (сек),oder_total,offline_free_total,соотношение,oder_avrg
145,2017-08-18 01:00:22.270,803,568082,606,317087,588,280699,658,845641,1512,2399981,1552,4411490,1443427,2968063,0.48632,477.379252

In [31]:
df[(df['Дата'] >= '02:00:00.000') & (df['Дата'] < '05:00:00.000')].head()

Empty DataFrame
Columns: [Дата, free_Кол-во водителей, free_Время (сек), order_driving_Кол-во водителей, order_driving_Время (сек), order_waiting_Кол-во водителей, order_waiting_Время (сек), order_transporting_Кол-во водителей, order_transporting_Время (сек), offline_Кол-во водителей, offline_Время (сек), Всего_Кол-во водителей, Всего_Время (сек), oder_total, offline_free_total, соотношение, oder_avrg]
Index: []

In [39]:
df['transport_to_total'] = df['order_transporting_Время (сек)']/df['Всего_Время (сек)']
df[df['transport_to_total'] == df['transport_to_total'].max()]

,Дата,free_Кол-во водителей,free_Время (сек),order_driving_Кол-во водителей,order_driving_Время (сек),order_waiting_Кол-во водителей,order_waiting_Время (сек),order_transporting_Кол-во водителей,order_transporting_Время (сек),offline_Кол-во водителей,offline_Время (сек),Всего_Кол-во водителей,Всего_Время (сек),oder_total,offline_free_total,соотношение,oder_avrg,transport_to_total
56,2017-08-14 07:59:59.720,1109,426158,968,585722,933,309881,984,1687474,1905,2192421,2057,5201656,2583077,2618579,0.986442,332.133976,0.324411

In [44]:
df[(df['Дата'] >= '2017-08-13 10:00:00.000') & (df['Дата'] < '2017-08-13 13:00:00.000')]['order_transporting_Время (сек)'].sum()

4503279

In [45]:
df[(df['Дата'] >= '2017-08-17 09:00:00.000') & (df['Дата'] < '2017-08-17 12:00:00.000')]['order_transporting_Время (сек)'].sum()

3592544

In [46]:
df[(df['Дата'] >= '2017-08-16 17:00:00.000') & (df['Дата'] < '2017-08-16 20:00:00.000')]['order_transporting_Время (сек)'].sum()

6345978

In [47]:
df[(df['Дата'] >= '2017-08-13 18:00:00.000') & (df['Дата'] < '2017-08-13 21:00:00.000')]['order_transporting_Время (сек)'].sum()

4180819