# Чтение и запись данных

In [2]:
import urllib.request as req
import json
import pandas as pd

## Урок 1. Чтение данных из web-сервиса

### Практика

#### Задание 1

Используя сервис MetaWeather, найдите идентификатор города Париж (Paris). Для запроса используйте адрес из следующей ячейки, заменив `%city%` на имя города.

In [4]:
url = "https://www.metaweather.com/api/location/search/?query=paris"

with req.urlopen(url) as session:
    response1 = session.read().decode()
    data = json.loads(response1)
city = data[0]['woeid']
city

615702

#### Задание 2

Используя полученный идентификатор города, запросите данные о погоде в Париже за 28 мая 2020 года. Для запроса используйте адрес из следующей ячейки, заменив `%city_id%`, `%year%`, `%month%`, `%day%` на идентификатор города, год, месяц и день соответственно.

In [10]:
url = 'https://www.metaweather.com/api/location/615702/2020/03/28/'

with req.urlopen(url) as session:
    response2 = session.read().decode()
    data = json.loads(response2)
df = pd.read_json(response2)
df

,id,weather_state_name,weather_state_abbr,wind_direction_compass,created,applicable_date,min_temp,max_temp,the_temp,wind_speed,wind_direction,air_pressure,humidity,visibility,predictability
0,5933403717238784,Light Cloud,lc,N,2020-03-28T21:36:04.550023Z,2020-03-28,4.740,12.905,12.485,5.861606,6.098695,1022.0,63,8.926308,70
1,5319736709611520,Clear,c,N,2020-03-28T18:36:04.571454Z,2020-03-28,5.065,17.680,16.545,5.210169,8.484989,1020.0,60,8.926308,68
2,5199323342045184,Clear,c,NNE,2020-03-28T15:36:05.015640Z,2020-03-28,5.065,17.680,16.545,5.478600,23.500000,1020.0,59,10.534106,68
3,5306123710103552,Heavy Cloud,hc,NNE,2020-03-28T12:36:04.501995Z,2020-03-28,5.025,16.750,15.375,5.447532,24.000000,1020.0,59,10.534106,71
4,5158675436011520,Heavy Cloud,hc,NNE,2020-03-28T09:36:04.806439Z,2020-03-28,5.005,15.955,15.465,5.533327,25.500000,1020.0,60,10.912832,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,5172037079269376,Heavy Cloud,hc,SSE,2020-03-20T12:36:28.571981Z,2020-03-28,5.250,16.050,14.050,1.938678,161.000000,1014.0,47,NaN,71
68,6399700397719552,Heavy Cloud,hc,SSE,2020-03-20T09:36:28.843051Z,2020-03-28,5.250,16.050,14.050,1.938678,161.000000,1014.0,47,NaN,71
69,5215621534973952,Heavy Rain,hr,SSE,2020-03-20T06:36:29.139762Z,2020-03-28,7.850,15.100,15.100,3.137925,157.000000,1014.0,45,NaN,77
70,4601818833223680,Heavy Rain,hr,SSE,2020-03-20T03:36:30.172220Z,2020-03-28,7.850,15.100,15.100,3.137925,157.000000,1014.0,45,NaN,77
71,5947129895845888,Heavy Cloud,hc,S,2020-03-20T00:36:29.722294Z,2020-03-28,7.970,15.750,14.590,1.174392,185.000000,1014.0,55,NaN,71

In [11]:
df['the_temp'].mean()

12.49659722222222