# Чтение и запись данных

In [2]:
import urllib.request as req
import json
import pandas as pd

## Урок 1. Чтение данных из web-сервиса

### Практика

#### Задание 1

Используя сервис MetaWeather, найдите идентификатор города Париж (Paris). Для запроса используйте адрес из следующей ячейки, заменив `%city%` на имя города.

In [4]:
url = "https://www.metaweather.com/api/location/search/?query=paris"

with req.urlopen(url) as session:
    response1 = session.read().decode()
    data = json.loads(response1)
city = data[0]['woeid']
city

615702

#### Задание 2

Используя полученный идентификатор города, запросите данные о погоде в Париже за 28 мая 2020 года. Для запроса используйте адрес из следующей ячейки, заменив `%city_id%`, `%year%`, `%month%`, `%day%` на идентификатор города, год, месяц и день соответственно.

In [12]:
url = 'https://www.metaweather.com/api/location/615702/2020/05/28/'

with req.urlopen(url) as session:
    response2 = session.read().decode()
    data = json.loads(response2)
df = pd.read_json(response2)
df

,id,weather_state_name,weather_state_abbr,wind_direction_compass,created,applicable_date,min_temp,max_temp,the_temp,wind_speed,wind_direction,air_pressure,humidity,visibility,predictability
0,6723109975490560,Clear,c,NE,2020-05-28T21:36:04.490586Z,2020-05-28,14.970,21.925,21.810,7.253747,45.331452,1028.0,43,15.078815,68
1,5582221102546944,Clear,c,NE,2020-05-28T18:36:05.696646Z,2020-05-28,13.895,24.470,24.165,7.170185,41.668908,1028.5,42,15.078815,68
2,4875719383449600,Clear,c,NE,2020-05-28T15:36:05.294001Z,2020-05-28,13.895,24.470,24.165,7.170185,41.668908,1028.5,42,15.078815,68
3,5781794072821760,Clear,c,NE,2020-05-28T12:36:04.965983Z,2020-05-28,13.865,23.555,22.340,7.230251,42.670098,1030.0,48,15.078815,68
4,5252630563520512,Clear,c,NE,2020-05-28T09:36:04.743683Z,2020-05-28,13.930,23.000,22.370,7.199636,43.334991,1030.0,47,14.516474,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,5687098029899776,Clear,c,N,2020-05-20T12:36:28.268133Z,2020-05-28,13.760,21.570,21.210,3.125497,359.000000,1026.0,38,NaN,68
68,6564044318179328,Clear,c,N,2020-05-20T09:36:28.742969Z,2020-05-28,13.760,21.570,21.210,3.125497,359.000000,1026.0,38,NaN,68
69,6519098827603968,Heavy Cloud,hc,NNW,2020-05-20T06:36:28.439998Z,2020-05-28,11.260,19.580,19.580,3.877356,335.000000,1024.0,44,NaN,71
70,5622980962942976,Heavy Cloud,hc,NNW,2020-05-20T03:36:29.023744Z,2020-05-28,11.260,19.580,19.580,3.877356,335.000000,1024.0,44,NaN,71
71,6540366297694208,Heavy Rain,hr,SSW,2020-05-20T00:36:28.339328Z,2020-05-28,13.570,31.070,30.550,3.554243,206.000000,1014.0,43,NaN,77

In [13]:
df['the_temp'].mean()

23.024791666666673