# Чтение и запись данных

In [1]:
import urllib.request as req
import json
import pandas as pd

## Урок 2. Чтение и запись файлов в формате JSON

### Практика

#### Задание 1 

Используя сервис MetaWeather, найдите идентификатор Москвы (Moscow). Для запроса используйте адрес из следующей ячейки, заменив `%city%` на имя города.

In [2]:
url = "https://www.metaweather.com/api/location/search/?query=moscow"
with req.urlopen(url) as session:
    response1 = session.read().decode()
    data = json.loads(response1)
city = data[0]['woeid']
city

2122265

#### Задание 2 

Используя полученный идентификатор города, запросите данные о погоде в Москве за 28 апреля 2020 года. Для запроса используйте адрес из следующей ячейки, заменив `%city_id%`, `%year%`, `%month%`, `%day%` на идентификатор города, год, месяц и день соответственно.

In [6]:
url = 'https://www.metaweather.com/api/location/2122265/2020/04/28/'

with req.urlopen(url) as session:
    response2 = session.read().decode()
    data = json.loads(response2)
df = pd.read_json(response2)
df

,id,weather_state_name,weather_state_abbr,wind_direction_compass,created,applicable_date,min_temp,max_temp,the_temp,wind_speed,wind_direction,air_pressure,humidity,visibility,predictability
0,4520607007899648,Showers,s,WNW,2020-04-28T18:27:32.227221Z,2020-04-28,3.670,10.915,9.965,4.550169,297.501335,1009.0,39,12.064543,73
1,5728158202462208,Showers,s,WNW,2020-04-28T15:27:32.320780Z,2020-04-28,3.670,10.915,9.920,4.550169,297.501335,1009.0,39,12.064543,73
2,5480870762774528,Showers,s,NW,2020-04-28T12:27:32.389465Z,2020-04-28,3.305,10.225,8.145,4.519929,308.334994,1009.5,51,12.064543,73
3,5972593918083072,Showers,s,NW,2020-04-28T09:27:32.493205Z,2020-04-28,3.195,9.915,8.025,4.555980,308.667384,1009.5,51,10.536902,73
4,5468569036914688,Showers,s,NW,2020-04-28T06:27:31.423059Z,2020-04-28,1.425,10.260,8.765,4.571307,308.667384,1009.5,47,12.849024,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,6250892430934016,Heavy Rain,hr,SSE,2020-04-20T09:27:56.706292Z,2020-04-28,4.940,14.560,13.830,2.193440,148.000000,1007.0,44,NaN,77
68,5886764499599360,Heavy Cloud,hc,W,2020-04-20T06:27:56.122840Z,2020-04-28,2.330,12.220,11.360,1.901396,281.000000,1014.0,41,NaN,71
69,6287126788308992,Heavy Cloud,hc,W,2020-04-20T03:27:55.833923Z,2020-04-28,2.330,12.220,11.360,1.901396,281.000000,1014.0,41,NaN,71
70,4568015662219264,Heavy Cloud,hc,NNE,2020-04-20T00:27:56.863059Z,2020-04-28,1.120,8.760,7.680,1.373230,15.000000,1014.0,49,NaN,71
71,6086405786697728,Heavy Cloud,hc,NNE,2020-04-19T21:27:55.595543Z,2020-04-28,1.120,8.760,7.680,1.373230,15.000000,1014.0,49,NaN,71

#### Задание 3 

Сохраните полученные данные в файл `file.json`. Для форматирования файла используйте четыре пробела.

In [7]:
with open('file.json', 'w') as file:
    json.dump(data, file, indent=4)

#### Задание 4 

Загрузите содержимое файла `file.json` в DataFrame и выведите первые пять строк на экран.

In [13]:
df = pd.read_json('file.json')
df.head()

,id,weather_state_name,weather_state_abbr,wind_direction_compass,created,applicable_date,min_temp,max_temp,the_temp,wind_speed,wind_direction,air_pressure,humidity,visibility,predictability
0,4520607007899648,Showers,s,WNW,2020-04-28T18:27:32.227221Z,2020-04-28,3.670,10.915,9.965,4.550169,297.501335,1009.0,39,12.064543,73
1,5728158202462208,Showers,s,WNW,2020-04-28T15:27:32.320780Z,2020-04-28,3.670,10.915,9.920,4.550169,297.501335,1009.0,39,12.064543,73
2,5480870762774528,Showers,s,NW,2020-04-28T12:27:32.389465Z,2020-04-28,3.305,10.225,8.145,4.519929,308.334994,1009.5,51,12.064543,73
3,5972593918083072,Showers,s,NW,2020-04-28T09:27:32.493205Z,2020-04-28,3.195,9.915,8.025,4.555980,308.667384,1009.5,51,10.536902,73
4,5468569036914688,Showers,s,NW,2020-04-28T06:27:31.423059Z,2020-04-28,1.425,10.260,8.765,4.571307,308.667384,1009.5,47,12.849024,73