# Тестовое задание на позицию Junior Analyst в IncognitoCompany
Тестовое задание состоит из 2 частей:

    a) задачи на логику, проверку знаний математики;

    b) задача, связанная с анализом данных, для проверки ваших технических
    навыков.

Если вы не можете по каким-то причинам выполнить целиком какое-либо задание, то
приведите те результаты, которых смогли достичь, а также напишите логику, по
которой вы бы стали его далее выполнять.
Ответы к техничеcкому заданию можно выложить:
* На Google Диск и отправить ссылку hr (открыв доступ на чтение);
* На github без указания компании и данных, на основе которых выполнено ТЗ, и отправить ссылку hr (не забудьте открыть доступ);
* Отправить hr.

Если результат тестового задания окажется успешным, мы свяжемся с вами. Ждем
ваших ответов. Удачи!
## 1. Вопросы:

    1) Как хорошо Вы владеете Python? Оцените свой уровень по шкале от 0 до 10, где 0 - совсем не знаю, 10 - владею в совершенстве. Объясните, почему Вы выбрали такой балл.
    
    2) Насколько хорошо Вы знакомы с Google Sheets? Оцените свой уровень по шкале от 0 до 10, где 0 - совсем не знаю, 10 - владею в совершенстве. Объясните, почему Вы выбрали такой балл.
    
## 2. Задачи на логику:

    1) Рекламная кампания стартовала вчера с дневным бюджетом 40$. Половина бюджета была израсходована к полудню, а 80% оставшегося бюджета было потрачено между полуднем и временем закрытия. Сколько долларов не было потрачено?

    2) 5 идентичных рекламных кампаний работали 24 дня по 6 часов в день, потрачено было 120 долларов. Сколько дней они работали бы на 216 долларов, если бы 9 одинаковых кампаний работали бы по 8 часов в день?

    3) Дизайнеры создали 200 рекламных баннеров для двух рекламных кампаний.80 из них не использовались ни в кампании №1, ни в кампании №2, 60 использовались только в кампании №1. И для каждого рекламного баннера, который использовался в обеих кампаниях, приходится 3 баннера, которые использовались только в кампании №2. Сколько баннеров было использовано в обеих рекламных кампаниях?

    4) Энн использует Instagram, но не Facebook, а Джон использует Youtube и Facebook. Кейт использует Youtube, но не Instagram, а Том использует Facebook, но не Youtube. Если каждый человек использует две из трех социальных сетей у кого предпочтения совпадают?

    5) Средний итоговый балл стажера по 4 модулям составляет 78 баллов. Сколько баллов должен получить стажер за 5-й модуль, чтобы средний балл по всему заданию составил 80?

    6) Заказанные в приложении товары доставляются на автомобиле. Автомобиль проезжает 260 км со средней скоростью 80 км / ч. На обратном пути машина движется со средней скоростью 100 км / ч. Насколько быстрее был обратный путь? Ответ указать в минутах.

## 3. Техническое задание
Техническое задание полностью выполняется с помощью языка программирования
Python. В таблице Excel НЕЛЬЗЯ вносить какие-либо изменения вручную.
В файле «data.xlsx» представлены данные по поступлению денежных средств от
клиентов компании N за покупку ее услуг.
Имеющиеся поля:

* client_id - ID клиента;
* sum – сумма денежных средств;
* status – статус оплаты;
* sale – менеджер, заключивший сделку;
* new/current – статус сделки;
* document – наличие оригинала подписанного договора с клиентом;
* receiving_date – дата получения оригинала договора.

## Вопросы:

    1) Вычислите общую выручку за июль 2021 по тем сделкам, приход денежных
    средств которых не просрочен.

    2) Как изменялась выручка компании за рассматриваемый период?
    Проиллюстрируйте графиком.

    3) Кто из менеджеров привлек для компании больше всего денежных средств в
    сентябре 2021?

    4) Какой тип сделок (новая/текущая) был преобладающим в октябре 2021?

    5) Сколько оригиналов договора по майским сделкам было получено в июне 2021?

## Задание:
За каждую заключенную сделку менеджер получает бонус, который рассчитывается
следующим образом.

    1) За новые сделки менеджер получает 7% от суммы, при условии, что статус оплаты «ОПЛАЧЕНО», а также имеется оригинал подписанного договора с клиентом (в рассматриваемом месяце).

    2) За текущие сделки менеджер получает 5% от суммы, если она больше 10 тыс., и 3 % от суммы, если меньше. При этом статус оплаты может быть любым, кроме «ПРОСРОЧЕНО», а также необходимо наличие оригинала подписанного договора с клиентом (в рассматриваемом месяце). Бонусы по сделкам, оригиналы для которых приходят позже рассматриваемого месяца, считаются остатком на следующий период, который выплачивается по мере прихода оригиналов. Вычислите остаток каждого из менеджеров на 01.07.2021.

In [1]:
import pandas as pd

In [4]:
df=pd.read_excel('D:\Download\data.xlsx')

In [6]:
df.head()

,client_id,sum,status,sale,new/current,Unnamed: 5,document,receiving_date
0,NaN,NaN,Май 2021,NaN,NaN,NaN,NaN,NaN
1,6.0,11693.7,ВНУТРЕННИЙ,-,-,NaN,-,-
2,14.0,5452.7,ОПЛАЧЕНО,Петрова,новая,NaN,оригинал,2021-07-26 00:00:00
3,15.0,13991.7,ОПЛАЧЕНО,Иванов,текущая,NaN,оригинал,2021-06-08 00:00:00
4,16.0,719.7,ОПЛАЧЕНО,Иванов,текущая,NaN,оригинал,2021-06-08 00:00:00